# Specifikace url a parametr? PostgreSQL ovlada?e
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=heslo123

# Automatické promítnutí logiky do ddl p?íkaz? a kontrola (v produkci doporu?eno 'validate')
spring.jpa.hibernate.ddl-auto=create-drop

# P?eklad formátování entit do logiky RDBMS (snake_case)
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

# Globální omezení vlivu opera?ního systému nad ?asovými strukturami
spring.jpa.properties.hibernate.jdbc.time_zone=UTC


# Logování SQL dotaz a jejich parametry pro lad?ní
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.jpa.properties.hibernate.format_sql=true


